### ISSUE TITLE
Error while executing the trivial pipeline using a trivial question

### ISSUE THREAD

**Issue by swathi-ssunder** [WDAqua/Qanary#18]
I follow the same steps as in the [tutorial](https://github.com/WDAqua/Qanary/wiki/Qanary-tutorial:-How-to-build-a-trivial-Question-Answering-pipeline) until Step 4.1. Then, when I enter the trivial question and **start QA process provided by Qanary**,  in the terminal running the Ambiverse NED component, I get the following error:

```
ERROR 8700 --- [nio-8010-exec-7] eu.wdaqua.qanary.ambiverse.AmbiverseNed : Process PEL:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0curl: (7) Failed to connect to 194.145.60.1 port 9400: Timed out
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0curl: (7) Failed to connect to 194.145.60.1 port 9400: Timed out
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0curl: (7) Failed to connect to 194.145.60.1 port 9400: Timed out
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0curl: (7) Failed to connect to 194.145.60.1 port 9400: Timed out
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0curl: (7) Failed to connect to 194.145.60.1 port 9400: Timed out
curl: (3) [globbing] unmatched close brace/bracket in column 8
100   237  100   215  100    22    135     13  0:00:01  0:00:01 --:--:--   137

2018-08-31 07:16:15.274 ERROR 8700 --- [nio-8010-exec-7] eu.wdaqua.qanary.ambiverse.AmbiverseNed  : Except: {}

org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:433) ~[json-20140107.jar!/:na]
        at org.json.JSONObject.<init>(JSONObject.java:194) ~[json-20140107.jar!/:na]
        at org.json.JSONObject.<init>(JSONObject.java:321) ~[json-20140107.jar!/:na]
        at eu.wdaqua.qanary.ambiverse.AmbiverseNed.process(AmbiverseNed.java:91) ~[qanary_component-NED-Ambiverse-1.0.1.jar!/:1.0.1]
        at eu.wdaqua.qanary.component.QanaryServiceController.annotatequestion(QanaryServiceController.java:66) [qa.component-1.0.0.jar!/:1.0.0]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) [spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) [spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) [spring-webmvc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]

```

I already checked that the Accesstoken for Ambiverse NED is being generated and the same token works when I test the same request individually through a curl command.

**Comment by jannlemm0913** [comment]
I am having the same issue. I am not very proficient yet with Qanary and its components, so I don't know where to look for the solution to this error. 
Have you found anything? Or should I use a different NED component (Ambiverse seems to have stopped its work on the project)?

**Comment by anbo-de** [comment]
The Ambiverse API seems to work up-to-now. The error message points towards a problem while reaching the Ambiverse API endpoint. I just checked it using the AmbiverseNED Qanary component. However, when the service is terminated, then we have to update the tutorial with another NED component.

@jannlemm0913 What is the exact message you receive? If the error is still occurring, then check the previous lines of your logfile/console, please. There the configuration of the curl command is shown.

**Comment by anbo-de** [comment]
Closed as outdated.
